import React,{useEffect,useRef} from 'https://esm.sh/react@18.3.1';
import {createRoot} from 'https://esm.sh/react-dom@18.3.1/client';
import htm from 'https://esm.sh/htm@3.1.1';
import {Player} from 'https://esm.sh/@remotion/player@4.0.0?deps=react@18.3.1,react-dom@18.3.1';
import {AbsoluteFill,interpolate,spring,useCurrentFrame,useVideoConfig} from 'https://esm.sh/remotion@4.0.0?deps=react@18.3.1';
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const html=htm.bind(React.createElement),clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'};
function Fruit({kind,x,y,s,o,r=0}){return html`<div className=${'fruit '+kind} style=${{left:x+'%',top:y+'%',transform:`translate(-50%,-50%) scale(${s}) rotate(${r}deg)`,opacity:o}}></div>`}
function JamHero(){const frame=useCurrentFrame(),{fps}=useVideoConfig(),p=interpolate(frame,[0,89],[0,1],clamp),pop=spring({frame:frame-7,fps,config:{damping:12,mass:.7,stiffness:80}}),spread=interpolate(pop,[0,1],[0,1]),imgScale=interpolate(p,[0,.5,1],[1.02,1.09,1.17]),imgOpacity=interpolate(p,[0,.62,1],[1,.82,.47]),titleY=interpolate(p,[0,.55,1],[0,-14,-52]),titleOpacity=interpolate(p,[0,.72,1],[1,.96,.2]),po=interpolate(p,[.12,.32,1],[0,1,1],clamp);return html`<${AbsoluteFill} style=${{background:'#2d0714',overflow:'hidden',fontFamily:'Georgia,serif'}}><img src=${window.GELEIAS_HERO} style=${{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',transform:`scale(${imgScale})`,opacity:imgOpacity}}/><${AbsoluteFill} style=${{background:'linear-gradient(180deg,rgba(22,3,9,.18),rgba(22,3,9,.72) 82%,rgba(22,3,9,.94))'}}/><div className="splash s1" style=${{transform:`translate(-50%,-50%) rotate(-30deg) scale(${spread})`,opacity:po}}></div><div className="splash s2" style=${{transform:`translate(-50%,-50%) rotate(25deg) scale(${spread})`,opacity:po}}></div><${Fruit} kind="berry" x=${50-31*spread} y=${50-15*spread} s=${.35+.75*spread} o=${po}/><${Fruit} kind="orange" x=${50+32*spread} y=${50-13*spread} s=${.34+.70*spread} o=${po} r=${35*spread}/><${Fruit} kind="passion" x=${50-22*spread} y=${50+24*spread} s=${.30+.60*spread} o=${po} r=${-28*spread}/><div style=${{position:'absolute',left:'50%',top:'48%',transform:`translate(-50%,calc(-50% + ${titleY}px))`,textAlign:'center',width:'min(90%,980px)',opacity:titleOpacity,color:'#fffaf2',textShadow:'0 4px 24px rgba(22,3,9,.35)'}}><div style=${{fontFamily:'DM Sans,system-ui',fontWeight:700,letterSpacing:4,textTransform:'uppercase',fontSize:16,marginBottom:18,color:'#f4d49d'}}>pequenos potes. grandes momentos.</div><h1 style=${{fontSize:'clamp(54px,9vw,118px)',lineHeight:.92,margin:0,fontWeight:500,letterSpacing:-4}}>Geleias Rosé</h1><p style=${{fontFamily:'DM Sans,system-ui',fontSize:'clamp(18px,2.2vw,28px)',lineHeight:1.45,margin:'24px auto 0',maxWidth:680,color:'#f9eee1'}}>Artesanais, intensas e feitas para transformar uma mesa simples em memória.</p></div><div style=${{position:'absolute',left:'50%',bottom:28,transform:'translateX(-50%)',fontFamily:'DM Sans,system-ui',color:'#fff6ea',fontSize:12,letterSpacing:2,textTransform:'uppercase',opacity:interpolate(p,[0,.28,.5],[.9,.9,0],clamp)}}>role para descobrir os sabores ↓</div></${AbsoluteFill}>`}
function Hero(){const section=useRef(null),player=useRef(null);useEffect(()=>{let raf=0;const update=()=>{if(!section.current||!player.current)return;const r=section.current.getBoundingClientRect(),travel=Math.max(1,r.height-innerHeight),progress=Math.min(1,Math.max(0,-r.top/travel));player.current.seekTo(Math.round(progress*89))};const onScroll=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(update)};section.current=document.getElementById('hero-scroll');update();addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll);return()=>{removeEventListener('scroll',onScroll);removeEventListener('resize',onScroll)}} ,[]);return html`<${Player} ref=${player} component=${JamHero} durationInFrames=${90} compositionWidth=${1440} compositionHeight=${900} fps=${30} controls=${false} autoPlay=${false} loop=${false} style=${{width:'100%',height:'100%'}}/>`}
const style=document.createElement('style');style.textContent=`.fruit{position:absolute;width:94px;height:94px;border-radius:50%;filter:drop-shadow(0 18px 18px #2b081955)}.fruit.orange{background:radial-gradient(circle,#fff6cd 0 9%,#ffdc75 10% 52%,#eea534 53% 70%,#c87021 71%)}.fruit.passion{background:radial-gradient(circle,#3a2418 0 5%,#ffce43 6% 53%,#e98620 54% 70%,#8b4316 71%)}.fruit.berry{background:radial-gradient(circle at 30% 25%,#c85878,#6b1937 50%,#310914 100%);box-shadow:-34px 12px 0 -10px #5b1530,30px 17px 0 -12px #7c2747,-4px 34px 0 -12px #451023}.splash{position:absolute;left:50%;top:48%;width:180px;height:65px;border-radius:60% 40% 55% 45%;background:linear-gradient(135deg,#a32850,#5b1128);transform-origin:center}.s1{margin-left:-220px;margin-top:-130px}.s2{margin-left:230px;margin-top:-90px}`;document.head.appendChild(style);createRoot(document.getElementById('remotion-root')).render(html`<${Hero}/>`);
document.querySelectorAll('.hero-photo').forEach(i=>i.src=window.GELEIAS_HERO);document.getElementById('year').textContent=new Date().getFullYear();
const cfg=window.SITE_CONFIG||{},digits=s=>(s||'').replace(/\D/g,''),chat=document.getElementById('chat'),open=()=>chat.hidden=false,close=()=>chat.hidden=true;document.querySelectorAll('.js-open-chat').forEach(b=>b.addEventListener('click',open));document.getElementById('close-chat').addEventListener('click',close);chat.addEventListener('click',e=>{if(e.target===chat)close()});
if(cfg.address){const enc=encodeURIComponent(cfg.address),card=document.getElementById('map-card'),a=document.getElementById('map-link'),copy=document.getElementById('address-copy');copy.textContent=cfg.address;copy.classList.remove('pending');a.href=`https://www.google.com/maps/search/?api=1&query=${enc}`;a.hidden=false;card.innerHTML=`<iframe title="Localização Geleias Rosé" src="https://www.google.com/maps?q=${enc}&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`}
let supabase=null;if(cfg.supabaseUrl&&cfg.supabaseAnon)try{supabase=createClient(cfg.supabaseUrl,cfg.supabaseAnon)}catch{}
document.getElementById('lead-form').addEventListener('submit',async e=>{e.preventDefault();const name=document.getElementById('lead-name').value.trim(),phone=digits(document.getElementById('lead-phone').value),store=digits(cfg.whatsapp),err=document.getElementById('form-error'),btn=document.getElementById('lead-submit');err.hidden=true;if(name.length<2||phone.length<10){err.textContent='Preencha seu nome e um WhatsApp válido.';err.hidden=false;return}if(!store){err.textContent='O WhatsApp da loja ainda não foi configurado.';err.hidden=false;return}btn.disabled=true;btn.textContent='Abrindo conversa…';if(supabase){try{await supabase.from('site_leads').insert({name,phone,source:'site-chat',status:'new'})}catch{}}const msg=`Olá! Meu nome é ${name}. Vi o site da Geleias Rosé e quero conhecer os sabores disponíveis.`;location.href=`https://wa.me/${store}?text=${encodeURIComponent(msg)}`});
