const BASE='https://qtxcqlzfqfckcjpeboeo.supabase.co';
const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0eGNxbHpmcWZja2NqcGVib2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3NzYzMjAsImV4cCI6MjEwMzM1MjMyMH0.ZBrUN6MD8XJ76Vz1RFvzZ-YbQa5f14Yb3G_ttej18SE';
const EDGE=BASE+'/functions/v1/md-agenda-whatsapp-notify';
const S={barbers:[],services:[],barber:null,service:null,date:null,slot:null};
const $=id=>document.getElementById(id);
async function rpc(name,body={}){const r=await fetch(BASE+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});let j=null;try{j=await r.json()}catch{}if(!r.ok)throw new Error(j?.message||'Não foi possível concluir.');return j}
function money(c){return(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function digits(v){return(v||'').replace(/\D/g,'')}function toast(t){$('toast').textContent=t;$('toast').classList.add('on');setTimeout(()=> $('toast').classList.remove('on'),2600)}
async function loadBrand(){try{const r=await rpc('md_agenda_brand');if(r?.[0]?.logo_url){$('brandLogo').src=r[0].logo_url;$('brandLogo').alt=r[0].name||'MDcortes'}}catch{}}
function photo(x,cls=''){return x.photo_url?`<img class="${cls}" src="${x.photo_url}" alt="${x.name}">`:`<span>${x.name.charAt(0)}</span>`}
async function loadBarbers(){try{S.barbers=await rpc('md_agenda_barbers');$('barbers').innerHTML=S.barbers.map(b=>`<button class="barber" data-id="${b.id}"><div class="avatar">${photo(b)}</div><div class="barberName">${b.name}</div><div class="barberHint">Ver agenda</div></button>`).join('');document.querySelectorAll('.barber').forEach(el=>el.onclick=()=>pickBarber(el.dataset.id))}catch(e){$('barbers').innerHTML=`<div class="empty">${e.message}</div>`}}
function pickBarber(id){S.barber=S.barbers.find(x=>x.id===id);S.service=S.date=S.slot=null;document.querySelectorAll('.barber').forEach(x=>x.classList.toggle('sel',x.dataset.id===id));$('chosenName').textContent=S.barber.name;$('miniAvatar').innerHTML=photo(S.barber);$('booking').classList.add('on');setSteps(1);slots();summary();setTimeout(()=> $('booking').scrollIntoView({behavior:'smooth',block:'start'}),120)}
$('changeBarber').onclick=()=>{S.barber=null;$('booking').classList.remove('on');document.querySelectorAll('.barber').forEach(x=>x.classList.remove('sel'));$('barberSection').scrollIntoView({behavior:'smooth'})};
async function loadServices(){try{S.services=await rpc('md_agenda_services');$('services').innerHTML=S.services.map(s=>`<button class="service" data-id="${s.id}"><div class="svcName">${s.name}</div><div class="svcMeta">${s.duration_minutes} min</div><div class="price">${s.price_on_request?'Consultar':money(s.price_cents)}</div></button>`).join('');document.querySelectorAll('.service').forEach(el=>el.onclick=()=>pickService(el.dataset.id))}catch(e){$('services').innerHTML=`<div class="empty">${e.message}</div>`}}
function pickService(id){S.service=S.services.find(x=>x.id===id);S.slot=null;document.querySelectorAll('.service').forEach(x=>x.classList.toggle('sel',x.dataset.id===id));setSteps(2);slots();summary()}
function makeDates(){let h='';const wd=new Intl.DateTimeFormat('pt-BR',{weekday:'short'}),mo=new Intl.DateTimeFormat('pt-BR',{month:'short'});for(let i=0;i<14;i++){let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);let iso=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');h+=`<button class="date" data-d="${iso}"><small>${wd.format(d).replace('.','')}</small><b>${d.getDate()}</b><small>${mo.format(d).replace('.','')}</small></button>`}$('dates').innerHTML=h;document.querySelectorAll('.date').forEach(el=>el.onclick=()=>pickDate(el.dataset.d))}
function pickDate(d){S.date=d;S.slot=null;document.querySelectorAll('.date').forEach(x=>x.classList.toggle('sel',x.dataset.d===d));setSteps(3);slots();summary()}
async function slots(){if(!S.barber||!S.service||!S.date){$('slots').innerHTML='<div class="empty">Escolha barbeiro, serviço e data.</div>';return}$('slotHint').textContent='consultando…';try{const a=await rpc('md_agenda_available_slots',{p_date:S.date,p_service_id:S.service.id,p_barber_id:S.barber.id});$('slotHint').textContent=a.length+' livres';$('slots').innerHTML=a.length?a.map(x=>`<button class="slot" data-at="${x.starts_at}">${x.label}</button>`).join(''):'<div class="empty">Nenhum horário livre para este barbeiro nesta data.</div>';document.querySelectorAll('.slot').forEach(el=>el.onclick=()=>{S.slot={at:el.dataset.at,label:el.textContent};document.querySelectorAll('.slot').forEach(x=>x.classList.toggle('sel',x===el));setSteps(4);summary()})}catch(e){$('slots').innerHTML=`<div class="empty">${e.message}</div>`}}
function setSteps(n){for(let i=1;i<=4;i++)$('st'+i).classList.toggle('on',i<=n)}function valid(){$('book').disabled=!(S.barber&&S.service&&S.date&&S.slot&&$('name').value.trim().length>=3&&digits($('phone').value).length>=10)}function summary(){if(S.barber&&S.service&&S.date&&S.slot){$('summary').classList.add('on');$('summary').innerHTML=`<div class="row"><span>Barbeiro</span><b>${S.barber.name}</b></div><div class="row"><span>Serviço</span><b>${S.service.name}</b></div><div class="row"><span>Data</span><b>${new Date(S.date+'T12:00:00').toLocaleDateString('pt-BR')}</b></div><div class="row"><span>Horário</span><b>${S.slot.label}</b></div><div class="row"><span>Valor</span><b>${S.service.price_on_request?'Consultar':money(S.service.price_cents)}</b></div>`}else $('summary').classList.remove('on');valid()}
$('name').oninput=valid;$('phone').oninput=valid;
async function notify(code,token,kind){try{const r=await fetch(EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,access_token:token,kind})});return await r.json()}catch{return null}}
$('book').onclick=async()=>{const old=$('book').textContent;$('book').disabled=true;$('book').textContent='CONFIRMANDO…';try{const r=await rpc('md_agenda_create_appointment',{p_customer_name:$('name').value.trim(),p_customer_phone:digits($('phone').value),p_service_id:S.service.id,p_barber_id:S.barber.id,p_starts_at:S.slot.at,p_notes:$('notes').value.trim()||null});const a=r[0];localStorage.setItem('mdcortes_last_booking',JSON.stringify({code:a.code,token:a.access_token}));$('successCode').textContent=a.code;$('successText').textContent=`Seu horário com ${a.barber_name} foi salvo com sucesso.`;$('successDetails').innerHTML=`<div class="row"><span>Barbeiro</span><b>${a.barber_name}</b></div><div class="row"><span>Serviço</span><b>${a.service_name}</b></div><div class="row"><span>Data e hora</span><b>${new Date(a.starts_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</b></div>`;const n=await notify(a.code,a.access_token,'created');const w=$('whatsLink');if(n?.fallback_url){w.href=n.fallback_url;w.classList.toggle('on',!n.sent)}else w.classList.remove('on');$('success').classList.add('on');await slots()}catch(e){toast(e.message.includes('Horário indisponível')?'Esse horário acabou de ser reservado. Escolha outro.':e.message);S.slot=null;await slots();summary()}finally{$('book').textContent=old;valid()}};
$('newBooking').onclick=()=>{$('success').classList.remove('on');S.service=S.date=S.slot=null;$('name').value='';$('phone').value='';$('notes').value='';document.querySelectorAll('.service,.date,.slot').forEach(x=>x.classList.remove('sel'));setSteps(1);summary();$('booking').scrollIntoView({behavior:'smooth'})};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$((b.dataset.close)).classList.remove('on'));
async function openMine(){const saved=JSON.parse(localStorage.getItem('mdcortes_last_booking')||'null');$('mineDetails').innerHTML='';$('cancelBtn').style.display='none';$('mineWhats').classList.remove('on');if(!saved){$('mineDetails').innerHTML='<div class="empty">Nenhum agendamento salvo neste celular.</div>';$('mine').classList.add('on');return}try{const r=await rpc('md_agenda_lookup_appointment',{p_code:saved.code,p_access_token:saved.token});const a=r[0];if(!a)throw new Error('Agendamento não encontrado.');$('mineDetails').innerHTML=`<div class="row"><span>Código</span><b>${a.code}</b></div><div class="row"><span>Barbeiro</span><b>${a.barber_name}</b></div><div class="row"><span>Serviço</span><b>${a.service_name}</b></div><div class="row"><span>Data e hora</span><b>${new Date(a.starts_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</b></div><div class="row"><span>Status</span><b>${a.status==='cancelled'?'Cancelado':a.status==='confirmed'?'Confirmado':'Aguardando'}</b></div>`;if(a.barber_whatsapp){$('mineWhats').href='https://wa.me/'+a.barber_whatsapp;$('mineWhats').classList.add('on')}if(['pending','confirmed'].includes(a.status)){$('cancelBtn').style.display='block';$('cancelBtn').onclick=()=>cancelMine(saved)}}catch(e){$('mineDetails').innerHTML=`<div class="empty">${e.message}</div>`}$('mine').classList.add('on')}
async function cancelMine(saved){if(!confirm('Deseja realmente cancelar este agendamento?'))return;try{await rpc('md_agenda_cancel_appointment',{p_code:saved.code,p_access_token:saved.token,p_reason:'Cancelado pelo cliente'});const n=await notify(saved.code,saved.token,'cancelled');toast('Agendamento cancelado. O horário foi liberado.');await openMine();if(n?.fallback_url&&!n.sent){$('mineWhats').href=n.fallback_url;$('mineWhats').textContent='AVISAR CANCELAMENTO NO WHATSAPP';$('mineWhats').classList.add('on')}}catch(e){toast(e.message)}}
$('myAppointment').onclick=openMine;
loadBrand();loadBarbers();loadServices();makeDates();