/**
 * Measured loudness of every audio asset, in dBFS.
 *
 * GENERATED by `tools/measure-levels.py` — do not edit by hand. Re-run it
 * (`npm run audio:levels`) after regenerating any audio.
 *
 * `mix.ts` uses these to work out the gain each file needs to land at its
 * target level relative to the voice. Without them a single gain cannot honour
 * the spec, because the assets do not share a starting level.
 *
 * Effects are measured over their loudest 300ms rather than whole-file: a
 * one-shot's decay tail would otherwise drag its average far below how loud it
 * actually sounds. Music, being continuous, is a whole-file average.
 */

/** RMS of the narration over its speaking parts, excluding pauses. */
export const NARRATION_DBFS = -23.3;

/** RMS of each asset as stored on disk. */
export const ASSET_DBFS: Record<string, number> = {
	'beep': -12.7,
	'beep-low': -13.1,
	'boom': -9.4,
	'chime': -11.5,
	'digital-sweep': -10.8,
	'glitch': -12.7,
	'hit-soft': -12.4,
	'impact-clean': -10.3,
	'impact-sub': -11.6,
	'low-whoosh': -8.0,
	'music': -20.8,
	'pop': -12.7,
	'pop-high': -12.0,
	'rise-clean': -6.9,
	'riser': -11.4,
	'shimmer': -11.7,
	'stamp': -17.0,
	'swipe': -18.2,
	'text-whoosh': -15.9,
	'tick': -24.2,
	'ui-click': -21.3,
	'whoosh': -12.9,
	'whoosh-soft': -14.6,
	'whoosh-stereo': -14.4,
};
