/**
 * Measured loudness of every audio asset, in dBFS.
 *
 * GENERATED by `tools/measure-levels.py` — do not edit by hand. Re-run it
 * (`npm run audio:levels`) after regenerating any audio.
 *
 * `mix.ts` uses these to work out the gain each file needs to land at its
 * target level relative to the voice. Without them a single gain cannot honour
 * the spec, because the assets do not share a starting level.
 */

/** RMS of the narration over its speaking parts, excluding pauses. */
export const NARRATION_DBFS = -23.3;

/** RMS of each asset as stored on disk. */
export const ASSET_DBFS: Record<string, number> = {
	'beep': -12.7,
	'beep-low': -13.1,
	'boom': -15.4,
	'chime': -20.0,
	'digital-sweep': -13.2,
	'glitch': -12.8,
	'hit-soft': -14.6,
	'impact-clean': -16.4,
	'impact-sub': -19.0,
	'low-whoosh': -11.1,
	'music': -20.8,
	'pop': -12.7,
	'pop-high': -12.0,
	'rise-clean': -12.2,
	'riser': -16.7,
	'shimmer': -15.8,
	'stamp': -18.5,
	'swipe': -18.5,
	'text-whoosh': -15.9,
	'tick': -24.2,
	'ui-click': -21.3,
	'whoosh': -15.1,
	'whoosh-soft': -15.9,
	'whoosh-stereo': -16.9,
};
