#!/usr/bin/env python3
"""
Measures the loudness of every audio asset and writes the calibration table
that `src/ConsulTech/mix.ts` uses.

Why this exists: the mix is specified as "effects 12-18 dB under the
narration". You cannot honour that with a fixed gain, because the assets do not
share a level — the narration sits at about -23 dBFS while a peak-normalised
effect sits nearer -13 dBFS, so applying -12 dB to the effect leaves it *above*
the voice. The gain each file needs is therefore

    gain_dB = (narration_dBFS - target_offset) - file_dBFS

which needs every file's actual level. This script measures them.

The narration is measured over speech only; its pauses would drag the average
down and make every effect too loud by the same amount.

Usage:  python3 tools/measure-levels.py
Writes: src/ConsulTech/levels.ts
"""

import glob
import json
import math
import os
import struct
import subprocess
import tempfile
import wave

ROOT = os.path.join(os.path.dirname(__file__), '..')
AUDIO = os.path.join(ROOT, 'public', 'audio')
OUT_TS = os.path.join(ROOT, 'src', 'ConsulTech', 'levels.ts')

FFMPEG = os.path.join(
    ROOT, 'node_modules', '@remotion', 'compositor-linux-x64-gnu', 'ffmpeg'
)
if not os.path.exists(FFMPEG):
    FFMPEG = 'ffmpeg'

SPEECH_GATE_DB = -45.0   # below this, a 50ms window counts as a pause


def decode(path, tmpdir):
    """mp3 -> mono 22.05k wav samples."""
    wav = os.path.join(tmpdir, os.path.basename(path) + '.wav')
    subprocess.run(
        [FFMPEG, '-v', 'error', '-i', path, '-ac', '1', '-ar', '22050',
         '-f', 'wav', wav, '-y'],
        check=True,
    )
    w = wave.open(wav)
    n = w.getnframes()
    return list(struct.unpack('<%dh' % n, w.readframes(n))), w.getframerate()


def rms_db(samples):
    if not samples:
        return -99.0
    r = math.sqrt(sum(v * v for v in samples) / len(samples))
    return 20 * math.log10(r / 32768) if r else -99.0


def loudest_window_db(samples, sr, window=0.30, hop=0.05):
    """
    RMS of the loudest `window` seconds.

    For a one-shot effect this is the number that matters. Whole-file RMS
    averages the attack together with a long decay tail, so a 2s impact whose
    energy all sits in the first 400ms measures ~10 dB quieter than it sounds —
    which is exactly how the first calibration ended up leaving effects level
    with the voice instead of well under it.
    """
    w = int(sr * window)
    if len(samples) <= w:
        return rms_db(samples)

    step = max(1, int(sr * hop))
    best = -99.0
    for i in range(0, len(samples) - w, step):
        best = max(best, rms_db(samples[i:i + w]))
    return best


def speech_rms_db(samples, sr):
    """RMS over the speaking parts only, ignoring the pauses between phrases."""
    win = int(sr * 0.05)
    voiced = []
    for i in range(0, len(samples) - win, win):
        seg = samples[i:i + win]
        if rms_db(seg) > SPEECH_GATE_DB:
            voiced.extend(seg)
    return rms_db(voiced if voiced else samples)


def main():
    with tempfile.TemporaryDirectory() as tmp:
        narration, sr = decode(os.path.join(AUDIO, 'narration.mp3'), tmp)
        narration_db = speech_rms_db(narration, sr)

        levels = {}
        music, _ = decode(os.path.join(AUDIO, 'music.mp3'), tmp)
        levels['music'] = round(rms_db(music), 1)

        for path in sorted(glob.glob(os.path.join(AUDIO, 'sfx', '*.mp3'))):
            name = os.path.splitext(os.path.basename(path))[0]
            samples, sfx_sr = decode(path, tmp)
            levels[name] = round(loudest_window_db(samples, sfx_sr), 1)

    narration_db = round(narration_db, 1)

    body = ',\n'.join(f"\t'{k}': {v}" for k, v in sorted(levels.items()))
    ts = f'''/**
 * Measured loudness of every audio asset, in dBFS.
 *
 * GENERATED by `tools/measure-levels.py` — do not edit by hand. Re-run it
 * (`npm run audio:levels`) after regenerating any audio.
 *
 * `mix.ts` uses these to work out the gain each file needs to land at its
 * target level relative to the voice. Without them a single gain cannot honour
 * the spec, because the assets do not share a starting level.
 *
 * Effects are measured over their loudest 300ms rather than whole-file: a
 * one-shot's decay tail would otherwise drag its average far below how loud it
 * actually sounds. Music, being continuous, is a whole-file average.
 */

/** RMS of the narration over its speaking parts, excluding pauses. */
export const NARRATION_DBFS = {narration_db};

/** RMS of each asset as stored on disk. */
export const ASSET_DBFS: Record<string, number> = {{
{body},
}};
'''
    with open(OUT_TS, 'w', encoding='utf-8') as f:
        f.write(ts)

    print(f'narration (speech only): {narration_db} dBFS')
    print(f'targets  → SFX {narration_db - 12:.1f} … {narration_db - 18:.1f} dBFS')
    print(f'         → music {narration_db - 24:.1f} … {narration_db - 30:.1f} dBFS')
    print(f'wrote {os.path.relpath(OUT_TS, ROOT)} with {len(levels)} assets')


if __name__ == '__main__':
    main()
